layout_spectrum: 1
typography_spectrum: 0.4241147
color:
  saturation: 0.4747049
  lightness: 0.7124789
  brandStrength: 0.4881956
  brandColors:
    - '#A0A098'
    - '#191B16'
    - '#8C8575'
    - '#F9E9B8'
    - '#605C50'
  rhythmicContrast: 0.4519393
name: Human Living
